name: mon_pacing
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.18.0
  country_flags: ^3.0.0
  cupertino_icons: ^1.0.6
  excel: ^4.0.3
  firebase_analytics: ^11.0.0
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.0
  firebase_performance: ^0.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_file_dialog: ^3.0.2
  flutter_foreground_task: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  flutter_material_color_picker: ^1.2.0
  freezed_annotation: ^2.4.1
  go_router: ^14.0.1
  google_fonts: ^6.1.0
  haptic_feedback: ^0.5.1
  hydrated_bloc: ^9.1.4
  intl: any
  isar: 
    version: ^4.0.3
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: ^4.0.3
    hosted: https://pub.isar-community.dev/
  json_annotation: ^4.8.1
  path_provider: ^2.1.2
  sanitize_filename: ^1.0.5
  textfield_tags: ^3.0.1
  toastification: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  golden_toolkit: ^0.15.0
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - google_fonts/
