name: mon_pacing
description: "Mobile app for improvisation match referees, based on Robert Gravel's idea to mix improv with hockey rules."
publish_to: "none"
version: 1.10.7+1

environment:
  sdk: ^3.9.0

dependencies:
  collection: ^1.18.0
  country_flags: ^4.0.1
  cupertino_icons: ^1.0.8
  dart_mappable: ^4.3.0
  dio: ^5.7.0
  excel: #^5.0.0
    git:
      url: https://github.com/justkawal/excel.git
      ref: main
  firebase_analytics: ^12.0.0
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_performance: ^0.11.0
  firebase_remote_config: ^6.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_file_dialog: ^3.0.2
  flutter_foreground_task: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  flutter_material_color_picker: ^1.2.0
  go_router: ^16.0.0
  haptic_feedback: ^0.5.1
  html: ^0.15.5
  hydrated_bloc: ^10.0.0
  intl: any
  introduction_screen: ^4.0.0
  mobile_scanner: ^7.0.0
  objectbox: ^5.0.0
  objectbox_flutter_libs: any
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.2
  recase: ^4.1.0
  sanitize_filename: ^1.0.5
  share_plus: ^12.0.0
  textfield_tags: ^3.0.1
  toastification: ^3.0.1
  tutorial_coach_mark: ^1.3.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  wakelock_plus: ^1.2.8

dev_dependencies:
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.3.0
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.5
  flutter_test:
    sdk: flutter
  golden_screenshot: ^4.0.1
  http_mock_adapter: ^0.6.1
  icons_launcher: ^3.0.1
  mockito: ^5.4.5
  objectbox_generator: any

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Poppins-Black.ttf
          weight: 900
        - asset: fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

  assets:
    - assets/

objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  # Or optionally specify the lib and test output folder separately.
  output_dir: repositories