name: mon_pacing
description: "A new Flutter project."
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_background_service_ios: ^5.0.0
  flutter_bloc: ^8.1.4
  flutter_local_notifications: ^16.3.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  hydrated_bloc: ^9.1.4
  intl: any
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  json_annotation: ^4.8.1
  path_provider: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true