name: mon_pacing
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

isar_version: &isar_version 4.0.2 # define the version to be used

dependencies:
  collection: ^1.18.0
  country_flags: ^2.2.0
  cupertino_icons: ^1.0.6
  excel: ^4.0.3
  firebase_analytics: ^10.8.6
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.15
  firebase_performance: ^0.9.3+14
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_colorpicker: ^1.0.3
  flutter_file_dialog: ^3.0.2
  flutter_foreground_task: ^6.1.3
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  freezed_annotation: ^2.4.1
  go_router: ^14.0.1
  google_fonts: ^6.1.0
  haptic_feedback: ^0.4.2
  hydrated_bloc: ^9.1.4
  intl: any
  isar: 
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  json_annotation: ^4.8.1
  objectbox: ^2.5.1
  path_provider: ^2.1.2
  sanitize_filename: ^1.0.5
  toastification:
    git: https://github.com/payam-zahedi/toastification

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  objectbox_generator: any

assets:
  - google_fonts/

flutter:
  uses-material-design: true
  generate: true
