name: install-flutter
description: Install Flutter
      
runs:
  using: composite
  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Restore packages
      shell: bash
      run: flutter pub get

    - name: Generate localization files
      shell: bash
      run: flutter gen-l10n