default_platform(:ios)

# Work around
# https://github.com/fastlane/fastlane/issues/20919
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "10" 
ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "10"

platform :ios do

  desc "Generate screenshots for Apple Store"
  lane :generate_screenshots do

    # Remove old screenshots
    Dir.chdir("./screenshots") do
      sh "rm -f ./*/*.png"
    end

    # Generate new screenshots
    Dir.chdir("../..") do
      sh "flutter test test/screenshots/generate_screenshots_test.dart --name=iOS --update-goldens"
    end

    # Frame screenshots
    frameit(path: "./fastlane/screenshots")

    # Remove unframed screenshots
    Dir.chdir("./screenshots") do
      sh "find . -type f \\( -path '*/*.png' -a ! \\( -path '*/*_framed.png' \\) \\) -delete"
    end

  end

  # options:
  #  - build_number
  #  - bundle_id
  #  - git_url
  #  - git_basic_authorization
  #  - upload_screenshots
  #  - upload_metadata
  #  - apple_team_id
  #  - apple_key_id
  #  - apple_issuer_id
  #  - apple_key_filepath (path)
  desc "Deploy a new build to the App Store"
  lane :build_deploy do |options|
    # Setup for CI
    setup_ci()

    # Get api_key from app store connect
    app_store_connect_api_key(
      key_id: options[:apple_key_id],
      issuer_id: options[:apple_issuer_id],
      key_filepath: options[:apple_key_filepath],
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    # Sync code signing
    sync_code_signing(
      type: "appstore",
      readonly: true,
      app_identifier: options[:bundle_id],
      team_id: options[:apple_team_id],
      api_key: lane_context[SharedValues::APP_STORE_CONNECT_API_KEY],
      generate_apple_certs: true,
      git_url: options[:git_url],
      git_basic_authorization: options[:git_basic_authorization],
      git_user_email: "ci@fastlane.tools",
      git_full_name: "Fastlane",
      git_branch: "main",
    )

    # Update code signing settings
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Runner.xcodeproj",
      targets: ["Runner"],
      build_configurations: ["Release"],
      team_id: options[:apple_team_id],
      bundle_identifier: options[:bundle_id],
      code_sign_identity: ENV["sigh_#{options[:bundle_id]}_appstore_certificate-name"],
      profile_name: ENV["sigh_#{options[:bundle_id]}_appstore_profile-name"],
      entitlements_file_path: "Runner/Runner.entitlements",
    )

    # https://docs.fastlane.tools/advanced/fastlane/#directory-behavior
    Dir.chdir("../..") do
      # https://docs.flutter.dev/deployment/cd#fastlane
      sh "flutter build ipa --release --build-number=#{options[:build_number]}"
    end

    # https://docs.flutter.dev/deployment/cd#fastlane
    build_app(
      skip_build_archive: true,
      scheme: "Runner",
      configuration: "Release",
      archive_path: "../build/ios/archive/Runner.xcarchive",
    )

    # Upload to App Store (Deliver)
    upload_to_app_store(
      app_identifier: options[:bundle_id],
      api_key: lane_context[SharedValues::APP_STORE_CONNECT_API_KEY],
      team_id: options[:apple_team_id],
      submit_for_review: true,
      automatic_release: true,
      force: true, # Skip HTML report verification
      precheck_include_in_app_purchases: false,
      skip_screenshots: !options[:upload_screenshots],
      overwrite_screenshots: true,
      skip_metadata: !options[:upload_metadata],
      reject_if_possible: true,
    )
  end

  # options:
  #  - bundle_id
  #  - git_url
  #  - git_basic_authorization
  #  - apple_team_id
  #  - apple_key_id
  #  - apple_issuer_id
  #  - apple_key_filepath (path)
  desc "Generate Certificate"
  lane :generate_cert do |options|

    # Setup for CI
    setup_ci()

    # Get api_key from app store connect
    app_store_connect_api_key(
      key_id: options[:apple_key_id],
      issuer_id: options[:apple_issuer_id],
      key_filepath: options[:apple_key_filepath],
      duration: 1200, # optional (maximum 1200)
      in_house: false, # Is App Store or Enterprise (in house) team
    )

    # Sync code signing 
    sync_code_signing(
      type: "appstore",
      readonly: false,
      app_identifier: options[:bundle_id],
      force: true,
      team_id: options[:apple_team_id],
      api_key: lane_context[SharedValues::APP_STORE_CONNECT_API_KEY],
      generate_apple_certs: true,
      git_url: options[:git_url],
      git_basic_authorization: options[:git_basic_authorization],
      git_user_email: "ci@fastlane.tools",
      git_full_name: "Fastlane",
      git_branch: "main",
    )
  end

end
