name: setup-flutter
description: Setup Flutter
      
runs:
  using: composite
  steps:
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.27.4

    - name: Initialize Flutter
      shell: bash
      run: |
        flutter pub get
        dart pub global activate flutterfire_cli