default_platform(:android)

platform :android do

  desc "Generate screenshots for Google Play Store"
  lane :generate_screenshots do

    # Remove old screenshots
    Dir.chdir("./metadata/android") do
      sh "rm -f ./*/images/*/*.png"
    end

    # Generate new screenshots
    Dir.chdir("../..") do
      sh "flutter test test/screenshots/generate_screenshots_test.dart --name=Android --update-goldens"
    end

    # Frame screenshots
    frameit(
      path: "./fastlane/metadata/android",
      use_platform: "ANY",
    )

    # Remove unframed screenshots
    Dir.chdir("./metadata/android") do
      sh "find . -type f \\( -path '*/images/*/*.png' -a ! \\( -path '*/images/*/*_framed.png' \\) \\) -delete"
    end

  end


  # options:
  #  - build_number
  #  - package_name
  #  - upload_screenshots
  #  - upload_images
  #  - upload_metadata
  #  - playstore_json_key (path)
  #     ** Requires a key.jks file in android/app directory and a key.properties file in android directory
  desc "Deploy a new build to the Google Play"
  lane :build_deploy do |options|

    # https://docs.fastlane.tools/advanced/fastlane/#directory-behavior
    Dir.chdir("../..") do
      # https://docs.flutter.dev/deployment/cd#fastlane
      sh "flutter build appbundle --release --build-number=#{options[:build_number]}"
    end

    # Upload to Google Play Store (Supply)
    upload_to_play_store(
      package_name: options[:package_name],
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      json_key: options[:playstore_json_key],
      track: "production",
      release_status: "completed",
      changes_not_sent_for_review: false,
      skip_upload_metadata: !options[:upload_metadata],
      skip_upload_changelogs: false,
      skip_upload_images: !options[:upload_images],
      skip_upload_screenshots: !options[:upload_screenshots],
    )
  end

end
