default_platform(:android)

platform :android do

  desc "Generate screenshots for Google Play Store"
  lane :generate_screenshots do

    # Remove old screenshots
    Dir.chdir("./metadata/android") do
      sh "rm -f ./*/images/*/*.png"
    end

    # Generate new screenshots
    Dir.chdir("../..") do
      sh "flutter test test/screenshots/generate_screenshots_test.dart --name=Android --update-goldens"
    end

    # Frame screenshots
    frameit(path: "./fastlane/metadata/android")

    # Remove unframed screenshots
    Dir.chdir("./metadata/android") do
      sh "find . -type f \\( -path '*/images/*/*.png' -a ! \\( -path '*/images/*/*_framed.png' \\) \\) -delete"
    end

  end


  # options:
  #  - package_name
  #  - upload_screenshots
  #  - upload_images
  #  - playstore_json_key (path)
  #  - aab (path)
  desc "Publish a build to Google Play"
  lane :build_deploy do |options|
    # Upload to Google Play Store (Supply)
    upload_to_play_store(
      package_name: options[:package_name],
      aab: options[:aab],
      json_key: options[:playstore_json_key],
      track: "production",
      release_status: "completed",
      changes_not_sent_for_review: false,
      skip_upload_metadata: false,
      skip_upload_changelogs: false,
      skip_upload_images: !options[:upload_images],
      skip_upload_screenshots: !options[:upload_screenshots],
    )
  end

end
