name: "Build & Deploy"

on:
  workflow_dispatch:
    inputs:
      skip-test:
        type: boolean
        description: 'Skip Tests'
        required: false
        default: false
      generate-screenshots:
        type: boolean
        description: 'Generate Screenshots'
        required: false
        default: false
      deploy-ios:
        type: boolean
        description: 'Deploy iOS'
        required: false
        default: true
      deploy-android:
        type: boolean
        description: 'Deploy Android'
        required: false
        default: true
      release_notes_fr_CA:
        type: string
        description: 'Release Notes (fr-CA):'
        required: true
      release_notes_en_CA:
        type: string
        description: 'Release Notes (en-CA):'
        required: true

jobs:
  set_build_number:
    name: Set Build Number
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.build_number_step.outputs.build_number }}
    steps:
      - name: Set Build Number
        id: build_number_step
        shell: bash
        run: |  
          BUILD_NUMBER=$(date +'%s')
          echo "## 🚀 Build Number: $BUILD_NUMBER" >> $GITHUB_STEP_SUMMARY
          echo "build_number=$BUILD_NUMBER" >> "$GITHUB_OUTPUT"

  tests:
    name: "Run Tests"
    needs: set_build_number
    permissions: write-all
    if: ${{ !cancelled() && !inputs.skip-test }}
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  build_deploy_ios:
    name: "Build & Deploy iOS"
    # Use macos-15 until macos-latest is updated to 15 - https://github.com/actions/runner-images/blob/main/README.md
    runs-on: macos-15 #macos-latest
    needs: [set_build_number, tests]
    if: ${{ !cancelled() && inputs.deploy-ios && needs.set_build_number.result == 'success' && (needs.tests.result == 'success' || needs.tests.result == 'skipped') }}
    environment: deploy-ios

    env:
      APPLE_KEY_FILE: apple_key.p8
      IOS_AUTH_KEY_BASE64: ${{ secrets.IOS_AUTH_KEY_BASE64 }}
      APPLE_KEY_ID: ${{ secrets.IOS_KEY_ID }}
      APPLE_ISSUER_ID: ${{ secrets.IOS_ISSUER_ID }}
      APPLE_TEAM_ID: ${{ secrets.IOS_TEAM_ID }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      GIT_BASIC_AUTHORIZATION: ${{ secrets.GIT_BASIC_AUTHORIZATION }}
      GIT_URL: "https://github.com/frederikstonge/mon-pacing-fastlane"

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: ./.github/actions/setup-flutter

      - name: Create Apple Required Files
        uses: gacts/run-and-post-run@v1.4.1
        with:
          working-directory: ios
          shell: bash
          run: |
            base64 -d <<< ${{ env.IOS_AUTH_KEY_BASE64 }} > ${{ env.APPLE_KEY_FILE }}
          post: |
            rm -f ${{ env.APPLE_KEY_FILE }}
      
      - name: Set Release Notes
        working-directory: ios
        shell: bash
        run: |
          echo "${{ github.event.inputs.release_notes_en_CA }}" > fastlane/metadata/en-CA/release_notes.txt
          echo "${{ github.event.inputs.release_notes_fr_CA }}" > fastlane/metadata/fr-CA/release_notes.txt

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'

      - name: Install Bundle
        working-directory: ios
        shell: bash
        run: |
          bundle install

      - name: Install ImageMagick
        if: ${{ inputs.generate-screenshots }}
        working-directory: android
        shell: bash
        run: |
          brew install ghostscript
          brew install imagemagick

      - name: Generate Screenshots
        working-directory: ios
        if: ${{ inputs.generate-screenshots }}
        shell: bash
        run: |
          fastlane generate_screenshots

      # - name: Run Fastlane
      #   working-directory: ios
      #   shell: bash
      #   run: |
      #     fastlane build_deploy \
      #       build_number:'${{ needs.set_build_number.outputs.build_number }}' \
      #       bundle_id:'com.stongef.monpacing' \
      #       git_url:'${{ env.GIT_URL }}' \
      #       git_basic_authorization:'${{ env.GIT_BASIC_AUTHORIZATION }}' \
      #       generate_screenshots:${{ inputs.generate-screenshots }} \
      #       apple_team_id:'${{ env.APPLE_TEAM_ID }}' \
      #       apple_key_id:'${{ env.APPLE_KEY_ID }}' \
      #       apple_issuer_id:'${{ env.APPLE_ISSUER_ID }}' \
      #       apple_key_filepath:'${{ env.APPLE_KEY_FILE }}'

  build_deploy_android:
    name: "Build & Deploy Android"
    runs-on: ubuntu-latest
    needs: [set_build_number, tests]
    if: ${{ !cancelled() && inputs.deploy-android && needs.set_build_number.result == 'success' && (needs.tests.result == 'success' || needs.tests.result == 'skipped') }}
    environment: deploy-android

    env:
      ANDROID_KEY_FILE: app/android-signing-key.jks
      ANDROID_KEY_PROPERTY_FILE: key.properties
      PLAYSTORE_KEY_FILE: playstore_key.json
      ANDROID_SIGNING_KEY_BASE64: ${{ secrets.ANDROID_SIGNING_KEY_BASE64 }}
      ANDROID_KEY_PROPERTIES_BASE64: ${{ secrets.ANDROID_KEY_PROPERTIES_BASE64 }}
      ANDROID_SERVICE_ACCOUNT_API_KEY_BASE64: ${{ secrets.ANDROID_SERVICE_ACCOUNT_API_KEY_BASE64 }}

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: ./.github/actions/setup-flutter


      - name: Create Android Required Files
        uses: gacts/run-and-post-run@v1.4.1
        with:
          working-directory: android
          shell: bash
          run: |
            base64 -d <<< ${{ env.ANDROID_SIGNING_KEY_BASE64 }} > ${{ env.ANDROID_KEY_FILE }}
            base64 -d <<< ${{ env.ANDROID_KEY_PROPERTIES_BASE64 }} > ${{ env.ANDROID_KEY_PROPERTY_FILE }}
            base64 -d <<< ${{ env.ANDROID_SERVICE_ACCOUNT_API_KEY_BASE64 }} > ${{ env.PLAYSTORE_KEY_FILE }}
          post: |
            rm -f ${{ env.ANDROID_KEY_FILE }}
            rm -f ${{ env.ANDROID_KEY_PROPERTY_FILE }}
            rm -f ${{ env.PLAYSTORE_KEY_FILE }}            

      - name: Set Release Notes
        working-directory: android
        shell: bash
        run: |
          echo "${{ github.event.inputs.release_notes_en_CA }}" > fastlane/metadata/android/en-CA/changelogs/default.txt
          echo "${{ github.event.inputs.release_notes_fr_CA }}" > fastlane/metadata/android/fr-CA/changelogs/default.txt

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'

      - name: Install Bundle
        working-directory: android
        shell: bash
        run: |
          bundle install

      - name: Install ImageMagick
        if: ${{ inputs.generate-screenshots }}
        working-directory: android
        shell: bash
        run: |
          sudo apt install ghostscript
          sudo apt install imagemagick

      - name: Generate Screenshots
        working-directory: android
        if: ${{ inputs.generate-screenshots }}
        shell: bash
        run: |
         fastlane generate_screenshots

      # - name: Run Fastlane
      #   working-directory: android
      #   shell: bash
      #   run: |
      #     fastlane build_deploy \
      #       build_number:'${{ needs.set_build_number.outputs.build_number }}' \
      #       package_name:'com.stongef.monpacing' \
      #       generate_screenshots:${{ inputs.generate-screenshots }} \
      #       playstore_json_key:'${{ env.PLAYSTORE_KEY_FILE }}'