name: "Generate Certificate iOS"

on:
  workflow_dispatch:   
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}   

jobs:
  generate_certificate_ios:
    name: "Generate Cerfificate iOS"
    runs-on: macos-latest
    environment: certificate

    env:
      APPLE_KEY_FILE: apple_key.p8
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      GIT_URL: "https://github.com/frederikstonge/mon-pacing-fastlane"

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Create Apple Key File
        uses: gacts/run-and-post-run@v1.4.1
        with:
          working-directory: ios
          shell: bash
          run: |
            base64 -d <<< ${{ secrets.IOS_AUTH_KEY_BASE64 }} > ${{ env.APPLE_KEY_FILE }}
          post: |
            rm -f ${{ env.APPLE_KEY_FILE }}

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'

      - name: Install Bundle
        working-directory: ios
        shell: bash
        run: |
          bundle install

      - name: Run Fastlane
        working-directory: ios
        shell: bash
        run: |
          bundle exec fastlane generate_cert \
            bundle_id:com.stongef.monpacing \
            git_url:${{ env.GIT_URL }} \
            git_basic_authorization:${{ secrets.GIT_BASIC_AUTHORIZATION }} \
            apple_team_id:${{ env.APPLE_TEAM_ID }} \
            apple_key_id:${{ env.APPLE_KEY_ID }} \
            apple_issuer_id:${{ env.APPLE_ISSUER_ID }} \
            apple_key_filepath:${{ env.APPLE_KEY_FILE }}